/* =============================================================================
   AS RUN SHEETS - RUN DATA
   This file IS the run sheets. Edit it, redeploy JUST this file, and every
   phone picks the change up on its next launch with signal. The app itself
   (index.html) does not need to change or be re-versioned for site edits.

   HOW TO EDIT
   - Change a site: edit its line. Anything in notes:'...' shows under Details.
   - Add a site:    copy an existing line inside the run's sites:[ ... ] list,
                    give it a NEW unique id, and edit the fields.
   - Remove a site: delete its whole {...}, line including the trailing comma.
   - Add a run:     copy a whole  XX:{label:...,shift:...,sites:[...]},  block
                    and give it a new key (e.g. A3). It appears in the dropdown
                    automatically.

   FIELDS (only id, name, addr, dur, req are required)
     id:'xyz'            unique, lowercase, NEVER change once used - logged
                         patrol times are stored against it
     name:'Site Name'    key:'B106152' (or null = "No keys")
     addr:'...'          full address (also the map link)
     dur:'10 min'        req:2                 patrols per night
     req:d=>WKEND.includes(d)?1:2              day-dependent count
     activeDays:WKEND    only these nights (MONFRI / WKEND / FRISUN or
                         ['Mon','Thu'])
     afterMin:T('22:30') all patrols after this time
     minGap:180          minutes required between patrols
     windows:[...]       one entry per patrol, in order:
                           BETWEEN('23:00','05:00')  a range
                           EXACT('22:30')            a set time
                           BEFORE('22:00')  AFTER('01:00')
                           AT('22:00',30)            time with +/- minutes
                         DST-dependent: windows:(d,dst)=>dst?[...]:[...]
     winLabels:['...']   short text on each Log button (same order)
     info:['Gate code 1234','After hours: Name 0400 000 000']
                         codes and phone numbers render big and tappable
     notes:'...'         full instructions; sentences become a checklist
     geo:{lat:-37.8,lng:144.9,radius:150}      optional geofence

   Times are 24h clock. The 45-minute compliance grace and the 90-minute
   default spacing live in index.html and apply automatically.

   AFTER EDITING: open the app once yourself. If you broke the syntax
   (a missing quote or comma), the app shows a data error screen instead
   of the run sheets - fix and redeploy.
   ============================================================================= */
const TOILET_NOTE='1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.';
const LIB_NOTE='2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.';
window.RUNS={
 A1:{label:'Allied 1', shift:'1800-0600', sites:[
  {id:'p2p1',name:'Paddock To Port (Pipe Rd)',key:null,addr:'46 Pipe Rd, Laverton North VIC 3026',dur:'5 min',req:1,windows:[BETWEEN('18:15','18:30')],winLabels:['Lock 1815-1830'],info:['Lock code 1985'],notes:'1x patrol. Lock the front gate at approximately 1830. Report any damage, graffiti, or suspicious activities.'},
  {id:'rcl',name:'RCL Group',key:'B106252',addr:'21 Regan St, St Albans VIC 3021',dur:'10 min',req:2,info:['Do not enter - construction site'],notes:'2x random external patrols. No need to enter the site - not safe due to construction. Check the fenceline and for any trespassers on site.'},
  {id:'acostar',name:'ACOSTAR',key:null,addr:'58 Boundary Rd, Sunshine West VIC 3020',dur:'10 min',req:1,info:['Gate code 6452','Front gates always open - no need to lock'],notes:'1x internal check of the yard ensuring doors are locked, no damage to property and no squatters on site.'},
  {id:'chris',name:'Chris\' Body Works',key:null,addr:'18-24 Burwood Rd, Sunshine North VIC 3020',dur:'10 min',req:1,notes:'1x external patrol making sure gates are secure and that there are no signs of break & enter.'},
  {id:'ssq',name:'Sunshine Square Shopping Centre',key:null,addr:'484 Ballarat Rd, Sunshine VIC 3020',dur:'15 min',req:2,windows:[EXACT('23:30'),BETWEEN('02:00','04:00')],winLabels:['Must be 2330','0200-0400'],notes:'2x patrols per night, one at 2300 and the other between 0200-0400.\nFirst patrol is the entire shopping complex. Full internal check of property, ensure all doors and gates are physically checked. Ensure each tenancy door is locked for all tenants who have ceased trading.\nSecond patrol is external only. Full visual check of the property and report any vehicles left in the car park. Remove any persons loitering around the complex.'},
  {id:'pcrs',name:'Premier Cranes & Rigging Sunshine',key:'B106198',addr:'7-8 Ovens Ct, Sunshine VIC 3020',dur:'10 min',req:d=>FRISUN.includes(d)?3:2,info:['Palgate app to open gate','Hi-vis vest at all times'],notes:'Intermittent check of premises. Hi-vis vest at all times. Use the Palgate app on your phone to open the gate - if you have issues, check that your bluetooth is on. The gate will record and report your time on site. 3rd hit only required Friday to Sunday.'},
  {id:'p2p2',name:'Paddock To Port (Fitzgerald Rd)',key:null,addr:'219-223 Fitzgerald Rd, Laverton North VIC 3026',dur:'5 min',req:1,windows:[BETWEEN('21:00','21:30')],winLabels:['Lock 2100-2130'],info:['Lock code 1964 or 3026'],notes:'1x patrol. Lock two sets of gates on either side of the warehouse at 2100. The code for the combination lock on the gates is 1964 or 3026.'},
  {id:'silver',name:'Silverchef',key:null,addr:'Unit 2/40 William Angliss Dr, Laverton North VIC 3026',dur:'10 min',req:2,notes:'2x external check of premises ensuring no damage to property and ensuring all gates and doors are secured.'},
  {id:'page',name:'Page Tasmanian Freight',key:'B106008',addr:'5 Maria St, Laverton North VIC 3026',dur:'15 min',req:3,notes:'3x patrols checking all doors and gates are secured.'},
  {id:'bridge',name:'Bridgestone Qts Factory',key:null,addr:'3/89 Boundary Rd, Laverton North VIC 3026',dur:'10 min',req:2,afterMin:T('22:00'),notes:'2x patrols of premises, 7 nights a week, after 2200.'},
  {id:'pcrl',name:'Premier Cranes & Rigging Laverton North',key:'B106198',addr:'69 Patch Cct, Laverton North VIC 3026',dur:'10 min',req:d=>FRISUN.includes(d)?3:2,info:['Palgate app to open gate','Hi-vis vest at all times'],notes:'Intermittent check of premises. Hi-vis vest at all times. Use the Palgate app on your phone to open the gate - if you have issues, check that your bluetooth is on. The gate will record and report your time on site. 3rd hit only required Friday to Sunday.'},
  {id:'land',name:'Landpower',key:'BS196956',addr:'31-33 Marshall Ct, Altona VIC 3018',dur:'10 min',req:2,windows:[BEFORE('22:00'),AFTER('01:00')],winLabels:['Before 2200','After 0100'],info:['Panel code 2684','Fenceline near freeway has been cut'],notes:'1x patrol before 2200 and 1x after 0100. Check the fenceline near the freeway as this has been cut. Do not open the gate. Enter via the parts warehouse on the left side driveway. Disarm the panel and go through the warehouse to check exterior doors.'},
  {id:'lead',name:'Leedwell - Altona',key:null,addr:'60 Toll Dr, Altona VIC 3018',dur:'10 min',req:2,info:['Lockbox code 4475*'],notes:'2x patrols per night. Enter the site using the keys from the lockbox and complete a full lap of the premises. Check SafetyCulture for more details.'},
  {id:'sami',name:'Sami Bitument',key:'BS196984',addr:'3 Oban Ct, Laverton VIC 3028',dur:'5 min',req:2,notes:'2x external check of premises ensuring all gates and doors are locked and no evidence of break and enter.'},
  {id:'warp',name:'Warpforge',key:null,addr:'471-479 Grieve Parade, Altona North VIC 3025',dur:'10 min',req:3,activeDays:MONFRI,windows:[EXACT('22:00'),EXACT('02:00'),EXACT('05:45')],winLabels:['Must be 2200','Must be 0200','Must be 0545'],info:['Padlock code 5472','Padlock 6039','Refer to SOP document'],notes:'3x patrols per night, Monday to Friday only. Must be at the designated times. Please refer to the SOP document for instructions.'},
  {id:'krug',name:'Krugar Transport',key:null,addr:'399 Boundary Rd, Truganina VIC 3029',dur:'10 min',req:2,windows:[null,BETWEEN('01:00','05:00')],winLabels:[null,'0100-0500'],notes:'2x patrols. 1x intermittent patrol between 0100-0500 ensuring no damage or fenceline damage and doors/gates are secure.'},
  {id:'chep',name:'Chep',key:'B106152',addr:'468 Boundary Rd, Derrimut VIC 3030',dur:'10 min',req:d=>MONFRI.includes(d)?2:1,info:['Call Chep to open boom gates'],notes:'2x patrols Monday to Friday. 1x patrol on weekends. Call the Chep phone number in your mobile to open the boom gates. Check and card all doors.'},
  {id:'jak',name:'Jakmax Pty Ltd',key:null,addr:'380 Foleys Rd, Derrimut VIC 3030',dur:'5 min',req:2,notes:'2x external check of premises ensuring no damage to property and ensuring all gates and doors are secured.'},
  {id:'tech',name:'Techwool Trading',key:'BS196981',addr:'290 Boundary Rd, Derrimut VIC 3030',dur:'10 min',req:2,notes:'2x external check of premises ensuring no damage to property and ensuring all gates and doors are secured.'},
  {id:'wmc',name:'William Mcniel',key:'B106505',addr:'400 Foleys Rd, Derrimut VIC 3030',dur:'5 min',req:2,info:['1 remote control - 4 gates'],notes:'2x internal check of premises ensuring no damage to property and ensuring all gates and doors are secured.'},
  {id:'shell',name:'Old Shell Petrol Station',key:null,addr:'25 Melton Hwy, Taylors Lakes VIC 3038',dur:'5 min',req:2,windows:[BETWEEN('23:00','05:00'),BETWEEN('23:00','05:00')],winLabels:['After 2300','Before 0500'],notes:'2x external patrols per night between 2300-0500. Ensure the service station is secured and that there is no new damage/graffiti or suspicious persons on site. Please also check the dispensers and vending machines. Report any damage.'},
  {id:'water',name:'Watervale Shopping Centre',key:'B106185',addr:'2-14 Calder Park Dr, Taylors Hill VIC 3037',dur:'10 min',req:3,windows:[EXACT('23:00'),AFTER('02:00'),AFTER('02:00')],winLabels:['Lock up 2300','Patrol from 0200','Patrol from 0200'],info:['Code 2244','Lower pad bolts into ground on every lock up','Closed Good Friday - patrol and check doors only'],notes:'1x lock/seal up and 2x patrols from 0200. When locking the auto doors you need to lower the pad bolts into the ground to secure the door on every lock up.'}
 ]},
 A9:{label:'Allied 9 Boroondara', shift:'1630-0030', sites:[
  {id:'maranoa',name:'Maranoa Gardens & Beckett Park Tower',key:'BS196867',addr:'30 Parring Rd, Balwyn VIC 3103',dur:'30 min',req:1,windows:[BETWEEN('16:45','17:00')],winLabels:['Lock 1645-1700'],info:['Start lockup from 1645','Do NOT lock Parring Rd car park gate'],notes:'Start lockup from 1645. Lock up of Maranoa Gardens and the Beckett Park Tower. Follow the instructions and photos closely in the SafetyCulture report. Do not lock the Parring Rd (car park) gate - A13 will lock this later in the night.'},
  {id:'hislop',name:'Hislop Park Toilets',key:'BS196998',addr:'209 Balwyn Rd, Balwyn North VIC 3104',dur:'5 min',req:1,windows:(d,dst)=>dst?[BETWEEN('20:00','21:00')]:[BETWEEN('19:00','20:00')],winLabels:(d,dst)=>dst?['Lock 2000-2100']:['Lock 1900-2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nBetween 2000-2100 during daylight savings, and 1900-2000 during non-daylight savings.'},
  {id:'willsmere',name:'Willsmere (Outer Circle Linear Park) Toilets',key:'BS196998',addr:'27 Willow Gr, Kew East VIC 3102',dur:'5 min',req:1,windows:(d,dst)=>dst?[BETWEEN('20:00','21:00')]:[BETWEEN('19:00','20:00')],winLabels:(d,dst)=>dst?['Lock 2000-2100']:['Lock 1900-2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nBetween 2000-2100 during daylight savings, and 1900-2000 during non-daylight savings.'},
  {id:'vicpark',name:'Victoria Park Playground Toilets',key:'BS196998',addr:'490 High St, Kew VIC 3101',dur:'5 min',req:1,windows:(d,dst)=>dst?[BETWEEN('20:00','21:00')]:[BETWEEN('19:00','20:00')],winLabels:(d,dst)=>dst?['Lock 2000-2100']:['Lock 1900-2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nBetween 2000-2100 during daylight savings, and 1900-2000 during non-daylight savings.'},
  {id:'kewtraffic',name:'Kew Traffic School Toilets',key:'BS196998',addr:'374 Cotham Rd, Kew VIC 3101',dur:'5 min',req:1,windows:(d,dst)=>dst?[BETWEEN('20:00','21:00')]:[BETWEEN('19:00','20:00')],winLabels:(d,dst)=>dst?['Lock 2000-2100']:['Lock 1900-2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nBetween 2000-2100 during daylight savings, and 1900-2000 during non-daylight savings.'},
  {id:'rathmines',name:'Rathmines Road (Angliss) Reserve Toilets',key:'BS196998',addr:'95 Rathmines Rd, Hawthorn East VIC 3123',dur:'5 min',req:1,windows:(d,dst)=>dst?[EXACT('21:00')]:[EXACT('20:00')],winLabels:(d,dst)=>dst?['Lock 2100']:['Lock 2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nAt 2100 during daylight savings, and 2000 during non-daylight savings.'},
  {id:'walpole',name:'Walpole St Toilet',key:'BS196998',addr:'2a Walpole St, Kew VIC 3101',dur:'5 min',req:1,windows:(d,dst)=>dst?[EXACT('21:00')]:[EXACT('20:00')],winLabels:(d,dst)=>dst?['Lock 2100']:['Lock 2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nAt 2100 during daylight savings, and 2000 during non-daylight savings.'},
  {id:'stjames',name:'St James Park Toilets',key:'BS196998',addr:'3 Burwood Rd, Hawthorn VIC 3122',dur:'5 min',req:1,windows:(d,dst)=>dst?[EXACT('21:00')]:[EXACT('20:00')],winLabels:(d,dst)=>dst?['Lock 2100']:['Lock 2000'],notes:'1x lock up. Check all toilets for damage/graffiti and suspicious/homeless persons. If all clear, lock the toilet.\nAt 2100 during daylight savings, and 2000 during non-daylight savings.'},
  {id:'balwynlib',name:'Balwyn Library',key:'BS196998',addr:'336 Whitehorse Rd, Balwyn VIC 3103',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'greythorn',name:'Greythorn Community Hub',key:'BS196998',addr:'2 Centre Way, Balwyn North VIC 3104',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'brabian',name:'Brabian Investments',key:null,addr:'660 Doncaster Rd, Doncaster VIC 3108',dur:'10 min',req:2,notes:'2x intermediate patrols. Check all doors & windows. Ensure car park is locked and fence line is all clear.'},
  {id:'cbg',name:'Camberwell Boys Grammar',key:null,addr:'2 Leason St, Kew East VIC 3102',dur:'10 min',req:1,windows:[EXACT('22:30')],winLabels:['Must be 2230'],notes:'1x external patrol at 2230 hours. The property belongs to CGS and is a new small pavilion with 6 tennis courts surrounding it. There is a park on one side and residences on the other. Check for any signs of vandalism and that the premise is secure.'},
  {id:'camgrammar',name:'Camberwell Grammar',key:'BS196862',addr:'55 Mont Albert Rd, Canterbury VIC 3126',dur:'30 min',req:1,windows:[BETWEEN('23:00','00:00')],winLabels:['2300-0000'],info:['Call Secure Corp 03 8527 5555 before entering','Foot patrol - CCTV is audited'],notes:'Call Secure Corp Monitoring before entering site (03 8527 5555). 1x 30 minute external patrol between 2300 and 0000 hours.\nEnter premises via all gates (gates 1-9) and patrol all areas. Patrol underground car park. Perform quick foot patrol around main buildings (please ensure foot patrol is completed as CCTV is audited). Make sure there is no sign of vandalism and that the premise is secure.'},
  {id:'alexandra',name:'Alexandra Gardens',key:'BS196998',addr:'70 Cotham Rd, Kew VIC 3101',dur:'10 min',req:2,minGap:120,notes:'2x patrols, at least 2-3 hours apart. Check for damage/graffiti on the pavilion and sculptures around the gardens. Check the garden shed and ensure it is locked with no damage/graffiti. Check the pond to ensure there is no rubbish dumped.'},
  {id:'kewlib',name:'Kew Library',key:'BS196998',addr:'Corner Cotham Road and Civic Dr, Kew VIC 3101',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'bradica',name:'S & O Bradica Kew',key:'BS196863',addr:'1-9 Derricks St, Kew VIC 3101',dur:'10 min',req:2,info:['Must check side door'],notes:'2x external checks of all doors and windows. Must check side door.'},
  {id:'kewcourt',name:'Kew Court House',key:'BS196998',addr:'188 High St, Kew VIC 3101',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'burwood260',name:'260 Burwood Rd, Ground Floor',key:'BS196866',addr:'260 Burwood Rd, Hawthorn VIC 3122',dur:'10 min',req:1,notes:'Check the lobby area before proceeding to the upper levels to check Xero offices.'},
  {id:'xero',name:'Xero',key:'BS196866',addr:'260 Burwood Rd, Hawthorn VIC 3122',dur:'10 min',req:1,info:['Ask for ID for any persons on site'],notes:'1x external/internal check of property. Must check the 3 sliding doors on Level 3 leading to the terrace. Check to ensure gates are secure and that there are no signs of break & enter. Must ask for ID for any persons on site.\nEnsure we check the side gate to the carpark and check each carpark level.'},
  {id:'hawthornprecinct',name:'Hawthorn Community Precinct',key:'BS196998',addr:'584 Glenferrie Rd, Hawthorn VIC 3122',dur:'7 min',req:2,minGap:180,info:['Swipe card entry','Meeting rooms may be in use late'],notes:'2x internal & external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons.\nEnter the building with your swipe card. Check the toilets (ground floor and Level 1), corridors, lights, storage cages and offices/meeting rooms on Level 1. Report any damages. The meeting rooms may be used by clients until late.'},
  {id:'hawthornarts',name:'Hawthorn Arts Centre',key:'BS196998',addr:'360 Burwood Rd, Hawthorn VIC 3122',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'mclean',name:'Mclean Demo Partners',key:null,addr:'312 Burwood Rd, Hawthorn VIC 3122',dur:'10 min',req:1,notes:'1x external check of property. Check all doors. Check to ensure gates are secure and that there are no signs of break & enter.'},
  {id:'freeway',name:'Freeway Golf Course',key:'BS196998',addr:'47-49 Columba St, Balwyn North VIC 3104',dur:'7 min',req:2,notes:'2x external patrols. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons.\nOnly perform an internal patrol if suspicious activity is found - otherwise not required.'},
  {id:'kewdepot',name:'Kew Depot',key:'BS196998',addr:'31 Hutchinson Dr, Kew VIC 3101',dur:'7 min',req:2,minGap:180,notes:'2x external patrols, at least 3 hours apart. Perform external perimeter check. Ensure the site is secured and there is no new damage/graffiti. Move on any homeless persons. Only perform an internal patrol if suspicious activity is found - otherwise not required.'}
 ]},
};
